// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proiect_Moldovan_Sonia.Data;

namespace Proiect_Moldovan_Sonia.Migrations
{
    [DbContext(typeof(Proiect_Moldovan_SoniaContext))]
    [Migration("20210109133407_EraPeriod")]
    partial class EraPeriod
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.Era", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EraName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EraPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Era");
                });

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.Museum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MuseumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketPrice")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Museum");
                });

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.Painting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MuseumID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MuseumID");

                    b.ToTable("Painting");
                });

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.PaintingEra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EraID")
                        .HasColumnType("int");

                    b.Property<int>("PaintingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EraID");

                    b.HasIndex("PaintingID");

                    b.ToTable("PaintingEra");
                });

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.Painting", b =>
                {
                    b.HasOne("Proiect_Moldovan_Sonia.Models.Museum", "Museum")
                        .WithMany("Paintings")
                        .HasForeignKey("MuseumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proiect_Moldovan_Sonia.Models.PaintingEra", b =>
                {
                    b.HasOne("Proiect_Moldovan_Sonia.Models.Era", "Era")
                        .WithMany("PaintingEras")
                        .HasForeignKey("EraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proiect_Moldovan_Sonia.Models.Painting", "Painting")
                        .WithMany("PaintingEras")
                        .HasForeignKey("PaintingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
